### ISSUE TITLE
[我成了！]问题

### ISSUE THREAD

**Issue by 931950483** [lzq-hopego/OpenMuZiClock#1]
转接板问题

**Comment by lzq-hopego** [comment]
电阻在接线图的最下方的屏幕转接板上，材料方面确实标错了，屏幕转接卡上需要两个电阻r1是5.1r，r2是20r均为1206封装，如果手头有那种长角的金属膜电阻也行












𝓛𝓸𝓿𝓮
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月12日(周一) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lzq-hopego/OpenMuZiClock] 5.1r贴片电阻两个，你这图里怎么没看到两个 (Issue #1)




 
采购清单写两个，但是我没看到接线图里有

**Comment by 931950483** [comment]
找不到你这种转接板，这种怎么接
![屏幕截图 2024-08-12 140604](https://github.com/user-attachments/assets/06d3fee0-1841-4b4f-a4ee-1d70aac1198e)

**Comment by 931950483** [comment]
就是我看不清楚电阻是串在转接板哪条线路上的，我觉得应该标出来

**Comment by 931950483** [comment]
还有就是5582光敏电阻是不是写错了，是不是5528

**Comment by lzq-hopego** [comment]
我使用的屏幕转接板是在pcb目录下的那个压缩包里的嘉立创打印的文件，使用嘉立创打印即可，上面的电阻和fpc插座需要自己焊接

**Comment by lzq-hopego** [comment]
光敏电阻的型号确实是5528

**Comment by 931950483** [comment]
我又发现有错误了，5mm间隔的排线插，应该是0.5mm

**Comment by 931950483** [comment]
东西准备好了，接下来就是等到货了XD

**Comment by lzq-hopego** [comment]
👍👍👍

**Comment by 931950483** [comment]
搞了一晚上，没成...我一直怀疑是我排线插座没焊好（电烙铁焊台），只要我接入屏幕，板子就会黑灯并且电脑没有端口显示，一拔掉屏幕就会重新亮灯并且显示有端口接入，我重新焊了好几次排插座都还是一样，最后甚至连电脑都已经不会有接入设备显示了，只有板子两个灯是亮的。是不是坏掉了？

**Comment by 931950483** [comment]
还有就是弹出要点重置按钮就是烧录进去了吗

**Comment by lzq-hopego** [comment]
你是bilibili上给我留言的那个人吧？关于接线可以先参看他的教程制作，我的只是在他基础上加了蜂鸣器和光敏电阻，关于烧录的问题，软件提示烧录失败，可以快速插拔并快速点击烧录等待进度跑完即可，或者使用esptool工具进行烧录(使用readme里的命令)，没有端口接入的情况可以尝试先按boot键再按rst键，关于屏幕黑屏白屏的问题，黑屏就是没焊好底座，白屏有可能是你自己编译的程序有问题或没焊好底座，如果烧录的是我的固件（如果白屏就是你焊接的问题），烧录成功后会开启muziclock热点，开启了则代表烧录上了

**Comment by 931950483** [comment]
烧录是最后提示验证完成之后显示点重置的，等我新板到了才能尝试了

**Comment by 931950483** [comment]
![微信图片_20240818232728](https://github.com/user-attachments/assets/b087e13f-e53d-485b-819e-ce39e2b65886)
我成了！

**Comment by lzq-hopego** [comment]
真棒👍

**Comment by 931950483** [comment]
如果可以支持亮度调节就好了
